//
//  ProjectIDsByTimeTargetsProducing.swift
//  TogglTargets
//
//  Created by David Dávila on 09.11.18.
//  Copyright 2016-2018 David Dávila
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation
import ReactiveSwift

/// An entity that receives a stream of collections of project IDs and produces a stream of `ProjectIDsByTimeTargets`
/// values and incremental updates generated by matching the received project IDs against the time targets and changes
/// to the time targets it has knowledge of.
protocol ProjectIDsByTimeTargetsProducing {

    /// Target that accepts and array of unsorted project IDs that will be matched against the time targets that this
    /// store has knowledge of.
    var projectIDs: BindingTarget<[ProjectID]> { get }

    /// Producer of `ProjectIDsByTimeTargets.Update` values that when started emits a `full(ProjectIDsByTimeTargets)`
    /// value which can be followed by full or incremental updates, corresponding to the `ProjectIDsByTimeTargets`
    /// generated by matching project IDs provided to the `projectIDs` target against the time targets this store knows
    /// about.
    var projectIDsByTimeTargetsProducer: ProjectIDsByTimeTargetsProducer { get }
}
